name: erply_assignment
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^2.4.0
  provider: ^3.0.0+1
  built_value:
  built_collection:
  overlay_support: ^1.0.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^2.4.0
  build_runner:
  built_value_generator:

  



flutter:
  uses-material-design: true
  assets: 
    - images/receptionist.png
    - images/key.png
    - images/settings.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
